-- SQL script to create the facts_assessment table in Postgres with clean headings
CREATE TABLE facts_assessment (
    "S.No - 0_level_1" TEXT,
    "STATE - 1_level_1" TEXT,
    "DISTRICT - 2_level_1" TEXT,
    "Rainfall (mm) - C" FLOAT,
    "Rainfall (mm) - NC" FLOAT,
    "Rainfall (mm) - PQ" FLOAT,
    "Rainfall (mm) - Total" FLOAT,
    "Total Geographical Area (ha) - C" FLOAT,
    "Total Geographical Area (ha) - NC" FLOAT,
    "Total Geographical Area (ha) - PQ" FLOAT,
    "Total Geographical Area (ha) - Total" FLOAT,
    "Total Geographical Area (ha) - Total.1" FLOAT,
    "Total Geographical Area (ha) - Total.2" FLOAT,
    "Ground Water Recharge (ham) - C" FLOAT,
    "Ground Water Recharge (ham) - NC" FLOAT,
    "Ground Water Recharge (ham) - PQ" FLOAT,
    "Ground Water Recharge (ham) - Total" FLOAT,
    "Ground Water Recharge (ham) - C.1" FLOAT,
    "Ground Water Recharge (ham) - PQ.1" FLOAT,
    "Ground Water Recharge (ham) - Total.1" FLOAT,
    "Ground Water Recharge (ham) - C.2" FLOAT,
    "Ground Water Recharge (ham) - NC.2" FLOAT,
    "Ground Water Recharge (ham) - PQ.2" FLOAT,
    "Ground Water Recharge (ham) - Total.2" FLOAT,
    "Ground Water Recharge (ham) - C.3" FLOAT,
    "Ground Water Recharge (ham) - NC.3" FLOAT,
    "Ground Water Recharge (ham) - PQ.3" FLOAT,
    "Ground Water Recharge (ham) - Total.3" FLOAT,
    "Ground Water Recharge (ham) - C.4" FLOAT,
    "Ground Water Recharge (ham) - NC.4" FLOAT,
    "Ground Water Recharge (ham) - PQ.4" FLOAT,
    "Ground Water Recharge (ham) - Total.4" FLOAT,
    "Ground Water Recharge (ham) - C.5" FLOAT,
    "Ground Water Recharge (ham) - NC.5" FLOAT,
    "Ground Water Recharge (ham) - PQ.5" FLOAT,
    "Ground Water Recharge (ham) - Total.5" FLOAT,
    "Ground Water Recharge (ham) - Total.8" FLOAT,
    "Ground Water Recharge (ham) - Total.9" FLOAT,
    "Ground Water Recharge (ham) - Total.10" FLOAT,
    "Ground Water Recharge (ham) - Total.11" FLOAT,
    "Inflows and Outflows (ham) - C" FLOAT,
    "Inflows and Outflows (ham) - NC" FLOAT,
    "Inflows and Outflows (ham) - PQ" FLOAT,
    "Inflows and Outflows (ham) - Total" FLOAT,
    "Inflows and Outflows (ham) - C.2" FLOAT,
    "Inflows and Outflows (ham) - NC.2" FLOAT,
    "Inflows and Outflows (ham) - PQ.2" FLOAT,
    "Inflows and Outflows (ham) - Total.2" FLOAT,
    "Inflows and Outflows (ham) - C.3" FLOAT,
    "Inflows and Outflows (ham) - NC.3" FLOAT,
    "Inflows and Outflows (ham) - PQ.3" FLOAT,
    "Inflows and Outflows (ham) - Total.3" FLOAT,
    "Inflows and Outflows (ham) - C.4" FLOAT,
    "Inflows and Outflows (ham) - NC.4" FLOAT,
    "Inflows and Outflows (ham) - PQ.4" FLOAT,
    "Inflows and Outflows (ham) - Total.4" FLOAT,
    "Inflows and Outflows (ham) - C.5" FLOAT,
    "Inflows and Outflows (ham) - NC.5" FLOAT,
    "Inflows and Outflows (ham) - PQ.5" FLOAT,
    "Inflows and Outflows (ham) - Total.5" FLOAT,
    "Inflows and Outflows (ham) - C.6" FLOAT,
    "Inflows and Outflows (ham) - NC.6" FLOAT,
    "Inflows and Outflows (ham) - PQ.6" FLOAT,
    "Inflows and Outflows (ham) - Total.6" FLOAT,
    "Inflows and Outflows (ham) - Total.7" FLOAT,
    "Inflows and Outflows (ham) - Total.8" FLOAT,
    "Inflows and Outflows (ham) - Total.9" FLOAT,
    "Inflows and Outflows (ham) - Total.10" FLOAT,
    "Annual Ground water Recharge (ham) - C" FLOAT,
    "Annual Ground water Recharge (ham) - NC" FLOAT,
    "Annual Ground water Recharge (ham) - PQ" FLOAT,
    "Annual Ground water Recharge (ham) - Total" FLOAT,
    "Environmental Flows (ham) - C" FLOAT,
    "Environmental Flows (ham) - NC" FLOAT,
    "Environmental Flows (ham) - PQ" FLOAT,
    "Environmental Flows (ham) - Total" FLOAT,
    "Annual Extractable Ground water Resource (ham) - C" FLOAT,
    "Annual Extractable Ground water Resource (ham) - NC" FLOAT,
    "Annual Extractable Ground water Resource (ham) - PQ" FLOAT,
    "Annual Extractable Ground water Resource (ham) - Total" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - C" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - NC" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - PQ" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - C.1" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - NC.1" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - PQ.1" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.1" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - C.2" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - NC.2" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - PQ.2" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.2" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.3" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.4" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.5" FLOAT,
    "Ground Water Extraction for all uses (ha.m) - Total.6" FLOAT,
    "Stage of Ground Water Extraction (%) - C" FLOAT,
    "Stage of Ground Water Extraction (%) - NC" FLOAT,
    "Stage of Ground Water Extraction (%) - PQ" FLOAT,
    "Stage of Ground Water Extraction (%) - Total" FLOAT,
    "Allocation of Ground Water Resource for Domestic Utilisation for projected year 2025 (ham) - C" FLOAT,
    "Allocation of Ground Water Resource for Domestic Utilisation for projected year 2025 (ham) - NC" FLOAT,
    "Allocation of Ground Water Resource for Domestic Utilisation for projected year 2025 (ham) - PQ" FLOAT,
    "Allocation of Ground Water Resource for Domestic Utilisation for projected year 2025 (ham) - Total" FLOAT,
    "Net Annual Ground Water Availability for Future Use (ham) - C" FLOAT,
    "Net Annual Ground Water Availability for Future Use (ham) - NC" FLOAT,
    "Net Annual Ground Water Availability for Future Use (ham) - PQ" FLOAT,
    "Net Annual Ground Water Availability for Future Use (ham) - Total" FLOAT,
    "Additional Potential Resources Under Specific Conditions(ham) - Waterlogged and shallow water Table" FLOAT,
    "Additional Potential Resources Under Specific Conditions(ham) - Flood Prone" FLOAT,
    "Additional Potential Resources Under Specific Conditions(ham) - Spring Discharge" FLOAT,
    "In-Storage Unconfined Ground Water Resources(ham) - Fresh" FLOAT,
    "In-Storage Unconfined Ground Water Resources(ham) - Saline" FLOAT,
    "Total Ground Water Availability in Unconfined Aquifier (ham) - Fresh" FLOAT,
    "Total Ground Water Availability in Unconfined Aquifier (ham) - Saline" FLOAT,
    "Dynamic Confined Ground Water Resources(ham) - Fresh" FLOAT,
    "In-Storage Confined Ground Water Resources(ham) - Fresh" FLOAT,
    "Total Confined Ground Water Resources (ham) - Fresh" FLOAT,
    "Total Ground Water Availability in the area (ham) - Fresh" FLOAT,
    "Total Ground Water Availability in the area (ham) - Saline" FLOAT
);
